name: CI - Run Tests

on:
  push:
    branches: [feature-branch]  # Run only on pushes to this branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub
      - name: Set up Python (replace with your desired version)
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      # Add steps to install dependencies
      - name: Install dependencies
        run: |   # Install dependencies based on your project needs
          python -m pip install -r requirements.txt
      # Add steps to run your tests
      - name: Run Unit Tests
        run: |
          python -m unittest discover TestUnit  # Replace with your test directory
      - name: Run Integration Tests (optional)
        run: |
          python -m pytest TestInteg 